import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("ObesityDataSet_raw_and_data_sinthetic.csv")

# ==========================================
# PLOT 1: Feature Correlation Heatmap
# ==========================================
plt.figure(figsize=(10, 8))  # 1. Open a clean figure
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Feature Correlation Heatmap")
plt.savefig("correlation_heatmap.png")
plt.close()                  # 2. Close it completely when done!

# ==========================================
# PLOT 2: Distribution of Obesity Levels
# ==========================================
plt.figure(figsize=(10, 5))  # 3. Open a brand new clean figure
# Assuming 'NObeyesdad' is your target obesity column
sns.countplot(data=df, y="NObeyesdad", order=df["NObeyesdad"].value_counts().index)
plt.title("Distribution of Obesity Levels")
plt.xlabel("Count")
plt.ylabel("Obesity Level")
plt.tight_layout()
plt.savefig("obesity_distribution.png")
plt.close()                  # 4. Close it completely!


# -*- coding: utf-8 -*-
"""Copy of DS_ASGM_CHART.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfPoXuKaj98pcJaG70IPvgYn-_kDUz4V
"""

# import pandas as pd
# import numpy as np
# from sklearn.preprocessing import StandardScaler
# from sklearn.model_selection import train_test_split

# # =========================================================================
# # 1. LOAD DATASET & DEDUPLICATION
# # =========================================================================
# # Read raw dataset
# df = pd.read_csv('Obesity.csv')

# # Remove duplicate records
# initial_rows = len(df)
# df = df.drop_duplicates()
# print(f"[INFO] Removed {initial_rows - len(df)} duplicate rows. New row count: {len(df)}")

# # Check for missing values
# missing_count = df.isnull().sum().sum()
# print(f"[INFO] Total missing values found: {missing_count}")

# import seaborn as sns
# import matplotlib.pyplot as plt

# # Set up the figure and axes
# fig, axes = plt.subplots(3, 1, figsize=(10, 15))

# # Iterate through each feature and plot the density plot
# for i, feature in enumerate(['Weight', 'Age', 'Height']):
#     sns.kdeplot(data=visual_df, x=feature, hue='NObeyesdad', ax=axes[i], fill=True, common_norm=False)
#     axes[i].set_title(f'Density Plot of {feature} by Target Variable')
#     axes[i].set_xlabel(feature)
#     axes[i].set_ylabel('Density')

# # Adjust layout
# plt.tight_layout()
# plt.show()

